spring:
  datasource:
    username: sa
    url: 'jdbc:sqlserver://localhost;databaseName=master;trustServerCertificate=true'
    password: digi@123
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
